/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // 1. Spring Context (само ядро Spring)
    implementation("org.springframework:spring-context:6.1.5")
// 2. Spring JDBC (еще понадобится для DataSource)
    implementation("org.springframework:spring-jdbc:6.1.5")
// 3. Spring ORM (интеграция Spring с Hibernate)
    implementation("org.springframework:spring-orm:6.1.5")
// 4. Spring Transaction (управление транзакциями)
    implementation("org.springframework:spring-tx:6.1.5")
// 5. Hibernate Core (сам ORM)
    implementation("org.hibernate.orm:hibernate-core:6.4.4.Final")
// 6. HikariCP (пул соединений)
    implementation("com.zaxxer:HikariCP:5.1.0")
// 7. H2 Database
    implementation("com.h2database:h2:2.2.224")
// 8. Spring Data JPA (наши репозитории)
    implementation("org.springframework.data:spring-data-jpa:3.2.5")
// 9. Jakarta Persistence (JPA аннотации)
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
// 10. Логгирование (чтобы видеть SQL)
    implementation("org.slf4j:slf4j-api:2.0.13")
    implementation("ch.qos.logback:logback-classic:1.5.6")




}



// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ru.bsuedu.cad.lab.app.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


allprojects {
    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
    }
}

tasks.withType<JavaExec> {
    systemProperty("file.encoding", "UTF-8")
}